GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "elon",
    "name": "Elon Musk",
    "password": "musk1234"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "ROOTUSER",
    "password": "root1234"
}