POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsb24iLCJpZCI6IjYzYWMwYzE2OTU0NzNjMWFlZTk2OTUxNiIsImlhdCI6MTY3MzAwOTEyOSwiZXhwIjoxNjczMDEyNzI5fQ.BFB0AFg4GX2UjjyLm_zRvlOP2bMvT22jiVXu7zL71gc

{
    "content": "Hi, everyone. I'm Yi Lan Ma.",
    "important": true,
    "userId": "63ac0c1695473c1aee969516"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{}

###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

###
# DELETE http://localhost:3001/api/notes/63a6fbcf0e59f927dab227ff

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Twitter is mine!",
    "important": true,
    "userId": "63ac0c1695473c1aee969516"
}