# get all patients
GET http://localhost:3001/api/patients

###
# get a patient by id
GET http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667

###
# get non-existent patient
GET http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155668

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "John Cena",
    "dateOfBirth": "1977-04-23",
    "ssn": "11111-111X",
    "gender": "male",
    "occupation": "professional wrestler",
    "entries": []
}

###
# date is in wrong form
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Elon Musk",
    "dateOfBirth": "yyyy-mm-dd",
    "ssn": "12345-678X",
    "gender": "male",
    "occupation": "comedian" ,
    "entries": []
}



