GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "John Cena",
    "dateOfBirth": "1977-04-23",
    "ssn": "11111-111X",
    "gender": "male",
    "occupation": "professional wrestler"
}

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Elon Musk",
    "dateOfBirth": "yyyy-mm-dd",
    "ssn": "12345-678X",
    "gender": "male",
    "occupation": "comedian" 
}



