GET http://localhost:3003/api/users

###
# Valid users
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "elonmusk",
    "name": "Elon Musk",
    "password": "ilovecatgirl"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "elon",
    "name": "John Cena",
    "password": "bingchilling"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "trump",
    "name": "Donald Trump",
    "password": "realdonaldtrump"
}

###
# Name is missing (valid)
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "1234"
}

###
# Username is missing (invalid)
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Mario",
    "password": "herewego"
}

###
# Invalid password length
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "luigi",
    "name": "Luigi",
    "password": "Ya"
}