###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "johncena",
    "password": "bingchilling"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5jZW5hIiwiaWQiOiI2M2FjNDk2NDVjOGIwMmU2ZmNlMDA5ZTciLCJpYXQiOjE2NzIzMTY3ODEsImV4cCI6MTY3MjMyMDM4MX0.4-UkmJDlWlCB9Jx4FhhemdKBhm3Uywc_dDVxuUXKPAk

{
    "title": "I love icecream",
    "author": "Some Chinese",
    "url": "http://example.com",
    "likes": 0
}

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/test